name: TREvaL
channels:
  - defaults
dependencies:
  - python = 3.8
  - pip
  - pip:
      - fairscale
      - fire
      - sentencepiece
      - numpy
      - matplotlib
      - torch  
      - transformers
      - pandas
      - datasets
      - rich
      - tqdm
      - deepspeed
      - tensorboard
      - wandb
      - accelerate
      - optree
  